### ISSUE TITLE
Externals Bar -- hover resize glitch

### ISSUE THREAD

**Issue by gisellegk** [team178/team178.github.io#103]
Only tested this on Chrome.... When you hover over the icons from the top, they behave as expected:
![screenshot from 2016-02-04 10 01 23](https://cloud.githubusercontent.com/assets/3026367/12819745/42987258-cb2a-11e5-8061-4d5f673e873a.gif)

However, when you hover from the bottom, it does this weird thing where the icons get displaced (moving the entire nav bar) and then going back and doing what it's supposed to do.
![screenshot2](https://cloud.githubusercontent.com/assets/3026367/12820000/4262a1a4-cb2b-11e5-99ab-c3b740981444.gif)

**Comment by TJScalzo** [comment]
The problem I've identified is that the margin of the `a tags` gets altered when they get hovered. This is done so that the height of the navigation bar doesn't change when the image enlarges. We run into the problem where weird stuff happens because the `a tag` gets hovered over before the image does. This means that the margin changes; moving the image up before it can be hovered and thus enlarged. This creates the effect shown in the gifs above.
Does that make sense? I'm not sure if that's _actually_ what's wrong; that's what it seems like to me.
