### ISSUE TITLE
Making "Meet Coaches & Mentors" page cool

### ISSUE THREAD

**Issue by EkVasilyeva** [team178/team178.github.io#138]
Hai. So I'm recently worked on a  new section of our page about our awesome mentors and coaches. The idea I got from this team's website: https://techtigers3654.org/page/mentors . I want to create something similar to that, so now I'm taking all info to fill the table. Specifically, I need help with:
1. What else can we add?
2. How to make it look interesting/cool?
3. What else can we add on this page?

I would appreciate all the help that I can get.

**Comment by TJScalzo** [comment]
I think it's coming along very well. It looks nice with the simple styling of the table. It would be interesting if we could include a headshot or some kind of photo of each person too. 

One part of the content that I would check is whether the position for each mentor/coach is correct.
I would take a look at Article VIII of the Bylaws and read the definitions of each position. Talking to each of the mentors or coaches to see how they define their position would also help.

- **Example 1:** As far as I know, Mrs. Hall and Mr. Barron didn't actually found the team. Although they have both been on the team for many years, I don't think either of them have been with the team since the very beginning.
- **Example 2:** Mrs. Hall and Mr. Barron are actually Co-_Head_ Coaches. This is an important distinction because it shows their increased level of involvement.
- **Example 2:** I believe Mr. Forstbauer is considered the Engineering Coach, not just a mentor.

**Comment by TJScalzo** [comment]
My other suggestions pertain to how the page fits into the structure of the site and other small nitpicks:
1. Remember that you can define a title for the page in the front matter of the file just like you defined the layout. The title of the page, the name used in navigation, and the URL don't necessarily have to match. But they should all have a level of consistency.
2. For example, in the [FIRST section](https://github.com/team178/team178.github.io/blob/master/_includes/navigation.html#L27), each page has a detailed title on their page, a shorter title in the navigation, and a simplified name for the URL. I would suggest adopting that type of scheme and move this page into the About section. Also keep in mind that verbs aren't really necessary in the navigation, so the name used for the URL could also be used for the navigation.
3. In terms of consistency, I would pick whether it's `Coaches & Mentors` or `Mentors & Coaches` and use the same order everywhere. (Personally, I think Mentors & Coaches sounds better.)
4. Since everything on this page is in HTML, I would just make it a `.html` file. That way, you don't have to wrap it in `<html>` tags.
5. Anytime the acronym _FIRST_ is used, it should be italicized. It's something that _FIRST_ requests in their branding standards and I've tried to keep it consistent on the website.
6. Play around with the default widths of the columns. It would be nice if "Parker Hannifin Fluid Control Division" didn't have to be on four lines.
7. Consider defining how the order that people are listed in is decided. That way, there's a clear reason an Alumni Mentor is listed above or below a regular Mentor.
8. Alumni Mentors are a defined type of mentor in the bylaws. I would suggest using that term rather than listing peoples' positions as Enforcer Alumna and mentor. (Since this page is talking in the context of mentors, giving the year an Alumni Mentor left the team may not be necessary.)

**Comment by TJScalzo** [comment]
All in all, I really like the direction this project is going. I'm glad to see both @EkVasilyeva and @FiveBillionHies are working together on this. Each of you has experience that is important to this project. I hope you can continue to work together and ask for each other's help when necessary.

**Comment by EkVasilyeva** [comment]
I think that we need to write a little paragraph about our mentors & coaches and how they impact our team and put on the top of the page. Since I'm not strong in English grammar, punctuation, and I'm in general not strong in writing, I don't think I'm a good candidate for this. What do y'all think?

**Comment by TJScalzo** [comment]
I think a quick summary or expression of thanks to mentors and coaches at the beginning of the page is a great idea!

**Comment by gisellegk** [comment]
@EkVasilyeva I think you could at least start a draft and get some other people to help you with grammar and editing! But also getting more people involved is a good thing too - no need to do everything yourself :D

**Comment by gisellegk** [comment]
Another suggestion - we have 2 woodie flowers award winners... why not brag about it on this page?

**Comment by TJScalzo** [comment]
It looks like this issue is close to being finished! From what I can see, there are three main things that need to be done:
- [ ] Finish writing summary paragraph
- [ ] Brag about our Woodie Flowers winners somewhere (?)
- [ ] Move this page's folder inside the `about` folder _(like the other pages in the about section)_
