### ISSUE TITLE
Fix Navigation Bar Responsiveness

### ISSUE THREAD

**Issue by meganlauren1211** [team178/team178.github.io#18]
formatting is messed up when we add/change the navigation so that it's longer. It'd be great to update the way things are placed on the page so that this isn't an issue.

**Comment by SilverSapo** [comment]
Increased max width of navigation bar

**Comment by gisellegk** [comment]
note that this is just a quick fix -- when I'm resizing the window here on my work computer it still doesn't place itself in the right spot with certain widths. We still need to look closer and possibly change how the webpage decides to place the social media bar.

**Comment by gluxon** [comment]
3 things. :)

1. Great use of Git Elizabeth. Linking code changes to issues about them may be helpful in the future. Take a look at -> https://github.com/blog/957-introducing-issue-mentions
2. Part of the reason the max-width was originally set to 1100px was to encourage 5-6 well thought out top level items. (e.g. Contact Us may be unnecessary since people are trained to look for information like that at the footer. Team History may fit under About.) Another reason is that monitors of 2000px width are still rare. In most cases, these high resolution monitors are set to a high dpi value (think retina) to scale it down to a lower pixel width.
3. A permanent fix for this issue would be to recode the navigation with the new CSS flexible box model layout. A really good article about it can be found here. http://chriswrightdesign.com/experiments/flexbox-adventures/ I'll help explain it during a meeting. Just ask. :)

**Comment by gluxon** [comment]
Closed by commit 0f98bb56a366548bf26d7e2d83be39fb48714adb
