### ISSUE TITLE
Social Media Bar Blocked by Adblock Plus

### ISSUE THREAD

**Issue by gisellegk** [team178/team178.github.io#19]
it's a default list on the adblock extension I'm using that blocks social media buttons.... idk how I feel about this because *technically* that's what it's supposed to do I guess, but I feel like the intent was to block things like those little facebook "like" buttons that some websites scatter all over their pages, rather than unintrusive icons on our navigation bar.

**Comment by gluxon** [comment]
I investigated this back when I implemented the social bar. Fanboy's social blocking list is very strict. Filenames like facebook.png are directly blocked. If we want to change this, we could rename the div to "externals" or the like.

**Comment by callmeStriking** [comment]
Or maybe you should respect the user agent's opinion and just let them block it instead of trying to circumvent it? If you block Facebook, you're not going to be clicking the button, are you?

**Comment by gluxon** [comment]
The #social-bar div is outright blocked, removing sites like GitHub as well. Like I said, if we want to change this, #externals-bar would help.

**Comment by gisellegk** [comment]
Yeah, facebook.png, etc. would probably still be blocked, but I feel like
that makes more sense than having the entire bar blocked.

(kind of off topic, but i think the site looks kind of bland without the
splash of color that the social media buttons give...)

On Thu, Feb 26, 2015 at 1:46 PM, Brandon Cheng <notifications@github.com>
wrote:

> The #social-bar div is outright blocked, removing sites like GitHub as
> well. Like I said, if we want to change this, #externals-bar would help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/team178/team178.github.io/issues/19#issuecomment-76240961>
> .
>



-- 
Giselle Koo

**Comment by nt1st** [comment]
If the site needs a splash of color, we should probably give it one
inpendent of third party icons.
On Thursday, February 26, 2015, Giselle <notifications@github.com> wrote:

> Yeah, facebook.png, etc. would probably still be blocked, but I feel like
> that makes more sense than having the entire bar blocked.
>
> (kind of off topic, but i think the site looks kind of bland without the
> splash of color that the social media buttons give...)
>
> On Thu, Feb 26, 2015 at 1:46 PM, Brandon Cheng <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > The #social-bar div is outright blocked, removing sites like GitHub as
> > well. Like I said, if we want to change this, #externals-bar would help.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/team178/team178.github.io/issues/19#issuecomment-76240961
> >
> > .
> >
>
>
>
> --
> Giselle Koo
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/team178/team178.github.io/issues/19#issuecomment-76244493>
> .
>


--

**Comment by nt1st** [comment]
*independent

On Thursday, February 26, 2015, Nandan T <t.nandan2008@gmail.com> wrote:

> If the site needs a splash of color, we should probably give it one
> inpendent of third party icons.
> On Thursday, February 26, 2015, Giselle <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Yeah, facebook.png, etc. would probably still be blocked, but I feel like
>> that makes more sense than having the entire bar blocked.
>>
>> (kind of off topic, but i think the site looks kind of bland without the
>> splash of color that the social media buttons give...)
>>
>> On Thu, Feb 26, 2015 at 1:46 PM, Brandon Cheng <notifications@github.com>
>> wrote:
>>
>> > The #social-bar div is outright blocked, removing sites like GitHub as
>> > well. Like I said, if we want to change this, #externals-bar would help.
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <
>> https://github.com/team178/team178.github.io/issues/19#issuecomment-76240961
>> >
>> > .
>> >
>>
>>
>>
>> --
>> Giselle Koo
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/team178/team178.github.io/issues/19#issuecomment-76244493>
>> .
>>
>
>
> --
>
>

--

**Comment by gluxon** [comment]
As long as Megan's good with it, suggestions welcome. :)

**Comment by callmeStriking** [comment]
[colourcode](http://colourco.de/) and [Adobe Color CC (née Kuler)](https://color.adobe.com/explore/most-popular/?time=all) are very helpful, free systems for choosing more colors. Personally I think the Pure Yellow on the website does not match "Enforcer Gold" and that the approximately Munsell 10B 3/2 that makes up the bar and background is too dark/blue.

Just for kicks, I decided to try [NCS-ing](https://en.wikipedia.org/wiki/Natural_Color_System) the colors (sans the text) just to see what it looked like. Using the [NCS Premium Navigator](http://www.ncscolour.com/en/premium-navigator/) (for which a free version that lacks color export exists [here](http://www.ncscolour.com/en/ncs-navigator/)), I picked colors NCS S 2060-B, NCS S 0580-Y, and NCS S 3060-B for the slideshow background, Enforcers logo, and nav-bar respectively. (Also, the Enforcers logo's font-weight had to be increased to "normal", because the color isn't really visible when the text is less than 1px thick. That and I was too lazy to change the text color, which needs a change when the other colors do.)

Here's what it looks like.
![2015-02-26-211233_1233x793_scrot](https://cloud.githubusercontent.com/assets/3682844/6406255/24e18a92-bdfc-11e4-9327-d2399485c62e.png)

For comparison, a "before" picture at the same resolution. 
![2015-02-26-211252_1233x793_scrot](https://cloud.githubusercontent.com/assets/3682844/6406256/288a42ce-bdfc-11e4-8736-2a8112afcf3c.png)

It looks way more playful and colorful now, in my opinion. Instead of adding more colors, it seems that sprucing up the ones we have is also a viable strategy. Clearly the prototype I've presented here needs some work but it's good even as a foil for discussion.

Thoughts?

**Comment by nt1st** [comment]
While I do agree with the need for vibrancy, I don't think that it should
come at the cost of brand identity, namely, the trademark Enforcers Blue
and Gold. Here is a Color CC swatch/palate that I made. The comments have
my personal frontrunners http://adobe.ly/183PqzR. If we were to change the
header color to the blue, and add yellow sidebars along the edges of the
content, at perhaps 5px, with a drop shadow onto the gray, then would
achieve slight vibrancy, while more completely representing our brand.
Here's a photoshop mockup. For detail on drop shadow, see the right panel,
as the left one diffused the drop shadow onto the blue header.

​


On Thu, Feb 26, 2015 at 9:19 PM, Rob Stolarz <notifications@github.com>
wrote:

> colourcode <http://colourco.de/> and Adobe Color CC (née Kuler)
> <https://color.adobe.com/explore/most-popular/?time=all> are very
> helpful, free systems for choosing more colors. Personally I think the Pure
> Yellow on the website does not match "Enforcer Gold" and that the
> approximately Munsell 10B 3/2 that makes up the bar and background is too
> dark/blue.
>
> Just for kicks, I decided to try NCS-ing
> <https://en.wikipedia.org/wiki/Natural_Color_System> the colors (sans the
> text) just to see what it looked like. Using the NCS Premium Navigator
> <http://www.ncscolour.com/en/premium-navigator/> (for which a free
> version that lacks color export exists here
> <http://www.ncscolour.com/en/ncs-navigator/>), I picked colors NCS S
> 2060-B, NCS S 0580-Y, and NCS S 3060-B for the slideshow background,
> Enforcers logo, and nav-bar respectively. (Also, the Enforcers logo's
> font-weight had to be increased to "normal", because the color isn't really
> visible when the text is less than 1px thick. That and I was too lazy to
> change the text color, which needs a change when the other colors do.)
>
> Here's what it looks like.
> [image: 2015-02-26-211233_1233x793_scrot]
> <https://cloud.githubusercontent.com/assets/3682844/6406255/24e18a92-bdfc-11e4-9327-d2399485c62e.png>
>
> For comparison, a "before" picture at the same resolution.
> [image: 2015-02-26-211252_1233x793_scrot]
> <https://cloud.githubusercontent.com/assets/3682844/6406256/288a42ce-bdfc-11e4-8736-2a8112afcf3c.png>
>
> It looks way more playful and colorful now, in my opinion. Instead of
> adding more colors, it seems that sprucing up the ones we have is also a
> viable strategy. Clearly the prototype I've presented here needs some work
> but it's good even as a foil for discussion.
>
> Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/team178/team178.github.io/issues/19#issuecomment-76319097>
> .
>



-- 
Nandan

**Comment by callmeStriking** [comment]
@nt1st GitHub doesn't actually allow you to email in image files... You have to manually add them to your post or otherwise obtain some URL to link in. Very interested to see what you've made, though.

Also, @all, maybe this discussion should go in a separate topic. I don't think it's on-topic here IMO.

**Comment by gluxon** [comment]
(Comments related to design deleted and moved to issue #21)

**Comment by gluxon** [comment]
Alright, I think renaming the #social-bar to #external-links-bar is appropriate in the code. It's a better name for it anyway. I've tested this change and Adblock Plus blocks everything but the GitHub link. This is also nice if we add an FRC link later.

Commit coming.

**Comment by gluxon** [comment]
Screenshot of fix with Fanboy's Social List on.

![only-github](https://cloud.githubusercontent.com/assets/906558/6659195/28e13018-cb56-11e4-9293-59b9783427fb.png)
