### ISSUE TITLE
Banner/Slideshow Usage

### ISSUE THREAD

**Issue by SilverSapo** [team178/team178.github.io#29]
There's the text banner on the top of every page with the image of the Claaaw and our introduction. It works for the home page, but for the other pages, it doesn't really fit. (Referred to as a slideshow in code, but it's not. Decide whether or not we want a slideshow or rename it.)

**Comment by gluxon** [comment]
It's setup in the code as a slideshow at the moment in case we want to add other slides of information. As for whether or not we need it on every page, I thought every page having a unique banner would have been ideal.

**Comment by gisellegk** [comment]
Please change the slideshow to something like "banner".  We are not using it as a slideshow, and it's confusing because we have a slideshow on the Media page. 

(Even if we did implement it with a unique slide for each page I think it would still make more sense to call it a banner, unless the slideshow actually moved or something.)

Here are all the files that need to be adjusted:
https://github.com/team178/team178.github.io/search?utf8=%E2%9C%93&q=slideshow

Also, the class called "slide" should be called something else that makes more sense once this change has been made.

**Comment by gisellegk** [comment]
@TJScalzo this was assigned to @anusha2617 ...?

**Comment by TJScalzo** [comment]
@Sorry, I didn't notice. I'll be more careful in the future.

**Comment by gisellegk** [comment]
:+1:

On Thu, Jan 28, 2016 at 11:54 PM, Tim Scalzo <notifications@github.com>
wrote:

> @Sorry <https://github.com/Sorry>, I didn't notice. I'll be more careful
> in the future.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/team178/team178.github.io/issues/29#issuecomment-176572366>
> .
>



-- 
Giselle Koo
