### ISSUE TITLE
Robot Header image looks weird in Firefox.

### ISSUE THREAD

**Issue by nt1st** [team178/team178.github.io#32]
![capture](https://cloud.githubusercontent.com/assets/10603428/6745445/4dbb988a-ce8d-11e4-88b8-3e8f4ca37821.PNG)

**Comment by gluxon** [comment]
Thanks to everyone for the work done today, but we should make sure to revert changes that don't quite work the way we expect as soon as possible.

In addition, for CSS or HTML changes, please run them locally to test them offline before committing to master. You should know exactly what the website looks like before officially uploading code. (Like programming for the robot.) This is a good software development practice. The article below details how to setup a local version of the team website. It's a little tricky, so feel free to ask for me for help.

https://help.github.com/articles/using-jekyll-with-pages/#installing-jekyll

You don't have to do this for content-only changes since prose.io has a preview for that.

**Comment by gisellegk** [comment]
The robot image looked fine from our computers yesterday, and from my iPad
that I'm typing from now... So this comes as a surprise. Will need to take
a closer look to see what is causing the issue for you guys.

Currently the website team does not have workstations with git even
installed much less Jekyll. Most of our commits were made on GitHub's
website.

There were a bunch of changes made that I would have reverted, but idk how
to revert on the website and didn't want to invest meeting time researching
that.

On Thursday, March 19, 2015, Brandon Cheng <notifications@github.com> wrote:

> Thanks to everyone for the work done today, but we should make sure to
> revert changes that don't quite work the way we expect as soon as possible.
>
> In addition, for CSS or HTML changes, please run them locally to test them
> offline before committing to master. You should know exactly what the
> website looks like before officially uploading code. (Like programming for
> the robot.) This is a good software development practice. The article below
> details how to setup a local version of the team website. It's a little
> tricky, so feel free to ask for me for help.
>
> https://help.github.com/articles/using-jekyll-with-pages/#installing-jekyll
>
> You don't have to do this for content-only changes since prose.io has a
> preview for that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/team178/team178.github.io/issues/32#issuecomment-83870775>
> .
>


-- 
Giselle Koo

**Comment by gisellegk** [comment]
![screenshot 2015-03-20 at 7 53 28 am](https://cloud.githubusercontent.com/assets/3026367/6751001/42d55908-ced6-11e4-9624-60547fb51ba9.png)

This is what I see on my chromebook at work...

**Comment by gisellegk** [comment]
- Right now the image is 432px x 518px, scaled down through css -- could be causing issues?? We might want this larger version on the Team History page, so maybe we should upload another smaller version?
- the right claw has a bit of not-transparent background that we missed.
- I think it would be a very good idea to learn to use git and test changes locally before committing, rather than trying to use the web interface. We just need to take the time to set up our computers and get used to the system. @SilverSapo and @Cytus26 have experience with git and should be able to help @meganlauren1211 and @adetoudomkh learn the ropes.

**Comment by gluxon** [comment]
Sorry for jumping to conclusions about the issue. That apology is for everyone that worked on this.

In the 20 minutes I spent on the problem, my guess is that `max-width` is a CSS property meant for box model elements and `flex-basis` should be used here instead. The discrepancies in Firefox and Chrome are probably due to areas in the W3C specifications that don't define how max-width behaves on a flex-item.

Since the flexible box model has a learning curve people are still working on and this problem isn't great to leave around, I'm going to assign this issue to myself. For members looking to tackle a flex box problem for learning, I'm going to refer you to issue #18.

Thanks everyone!
