### ISSUE TITLE
Hover Popup/Tooltips explaining colors of the raffle meter

### ISSUE THREAD

**Issue by TJScalzo** [team178/team178.github.io#39]
Possibly make the bar have popup text that says what the colors mean and maybe some other stuff. If that's too difficult it could just have a link to a page that explains everything.

**Comment by TJScalzo** [comment]
The separate page could have all of the different statistics if needed/wanted. 
**Ideas:** 
* % of total goal
* % of tickets checked out
* % of tickets checked out of total
* # of tickets needed to reach goal
* $ we've made in total 
* $ of profit

**Comment by TJScalzo** [comment]
I'm going to look into how to do this.

**Comment by TJScalzo** [comment]
[This website](http://www.nicolashoening.de/?twocents&nr=8) seems to offer an answer; I'm going to try and use it.

**Comment by gisellegk** [comment]
So I can't put individual tooltips on each color because they are pseudoclasses. This fix should be fine for now...

An improvement would be possible if we re-factor the large raffle meter to be made of three separate `<div>` elements (like the small one) rather than using `:before` and `:after`. This is because the tooltip is an `:after` pseudo element, and you can only have one of each on any particular real element.

**Comment by TJScalzo** [comment]
I think having only one tooltip should be fine. I'm going to make some adjustments to the words.
**This:**
Blue: Tickets sold
Yellow: Checked out books
White: Not touched yet
**Instead of:**
Blue: Tickets sold | Yellow:
Checked out books | White:
Not touched yet :(
It makes sense for each piece of info. to be on a separate line.
**Also, I'm going to try and do what's mentioned in #59.**

**Comment by gisellegk** [comment]
I couldn't get them on separate lines so I did the bars instead... but if you can fix it then good :+1: I didn't try for very long lol...

**Comment by TJScalzo** [comment]
I tried to do it for a little bit but I couldn't find the motivation to figure out how to do it.
