### ISSUE TITLE
StyleSheet() doesn't work in the else statement (Raffle Meter)

### ISSUE THREAD

**Issue by TJScalzo** [team178/team178.github.io#70]
When I tested in Jekyll it gave an error when trying to run this. 
![screen shot 2015-12-16 at 7 30 11 pm](https://cloud.githubusercontent.com/assets/15825214/11858390/280c386a-a42f-11e5-83c7-6cdce3e21daf.png)
I'm not really sure why it says that. Does it need something that I'm not including?

See: 0352d84606068cc2723b28efe8d95c9c548fb374 and [raffle-meter.js](https://github.com/team178/team178.github.io/blob/master/assets/js/raffle-meter.js)

**Comment by gluxon** [comment]
It looks like you have an `else`s at the end of that function without an if.

**Comment by gluxon** [comment]
Oh, I know what's happening. In your HTML, `raffle-meter.js` is included before `modifying-css.js`. Because your last `else` is outside of the `handleQueryResponse()` function, the code is trying to execute the `StyleSheet()` function before it even exists.

If you put it back inside the function, it should start working again since the function will be ran after the page is finished loading. (And all the javascript file code imports are done.)

**Comment by gisellegk** [comment]
I think I accidentally fixed this while doing some other stuff lol
