### ISSUE TITLE
Combine "Files" and "assets/img" folders

### ISSUE THREAD

**Issue by TJScalzo** [team178/team178.github.io#76]
I just found a folder that's called "files" and it's filled with random images. Are these the images that are missing (#66)? If not, why are they there? As far as I can see, only one of them is used on the site. I think they should be moved to the "img" folder for consistency's sake.

**Comment by gisellegk** [comment]
Yes they should be merged and all image links should be updated appropriately. And yes, it's possible that some of our missing images are here (perhaps the person who put the images in expected them to be in /assets/img )

If memory serves me correctly, I think the files folder came about when we tried to use [Prose.io](http://prose.io/) since the kids working on it at the time were only contributing content and did not want to learn git. :unamused:
