### ISSUE TITLE
Floating Nav Bar

### ISSUE THREAD

**Issue by nt1st** [team178/team178.github.io#98]
I've seen this all over the web, and I think it could be really cool. I think that we can technically do it. Any feedback?

**Comment by gisellegk** [comment]
If what you mean is a fixed-position nav bar that sticks with your screen no matter where you scroll, yes that would be very doable. 

I'm partial to ones that are larger, and shrink down after scrolling. [Udacity](https://www.udacity.com/) isn't the best example but you can see their logo is larger at the top of the page and also blends in with their banner pic.

**Comment by gluxon** [comment]
Worth trying for a while. It would be just a few lines of code to the #header element.

https://developer.mozilla.org/en-US/docs/Web/CSS/position#Sticky_positioning

**Comment by TJScalzo** [comment]
If we get this to work the flags could also move down with the navigation bar. (?)

**Comment by TJScalzo** [comment]
It seems like `position: -webkit-sticky` will work for this feature.

However, the new problem I've found is a very interesting one. When you set this property it causes the font-weight to become thinner on Safari because of the reasons given [here](https://stackoverflow.com/a/12350204). The semi-transparent pixels that the nav/header has is the shadow created using `border`.
