### ISSUE TITLE
Adjust Flag positioning for large screens

### ISSUE THREAD

**Issue by gisellegk** [team178/team178.github.io#99]
Here is a screenshot from a very pretty iMac with a nice big screen at RIT: 
![screen shot 2016-02-03 at 2 19 12 pm](https://cloud.githubusercontent.com/assets/3026367/12800768/8c6ddfb0-caa5-11e5-9444-5cff60738d13.png)

Lauren said the flags look weird when they're all the way on the edge of the page, since the rest of the stuff on the site is in the middle. 

Preferrably, the flags should hang right underneath the "Enforcers" logo and the externals bar.

**Comment by TJScalzo** [comment]
I'll look into implementing this.

**Comment by TJScalzo** [comment]
I've been messing around with flexboxes and nothing seems to work exactly right. I'm thinking that what we could do instead is just use a bunch of `@media` tags that change the width of the banners for different monitor widths.

**Comment by gisellegk** [comment]
Yeah I think @media would work. I would try to add to the existing screen sizes.

**Comment by TJScalzo** [comment]
I figured out why a problem that I was running into in trying to fix these was happening. I haven't actually made a way to do stuff yet... I'll hopefully have it done by the end of this meeting?
**Cool thing:**
By adding `transition: margin .5s` to the flags' CSS makes them slide between the Media queries instead of jumping to them. So... There's a cool thing...
